jobs:
  release-rolling:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: '*'
    - run: npm ci
    - run: npm run build
    - run: |
        npm pack --pack-destination=.github
        for file in .github/*.tgz; do mv "$file" "${file%-*}.tgz"; done
    - if: ${{github.ref == 'refs/tags/rolling'}}
      env:
        GH_TOKEN: ${{github.token}}
      run: |
        gh release upload rolling .github/*.tgz main.js manifest.json styles.css --clobber

on:
  push:
    tags:
    - rolling
  workflow_dispatch:

permissions: {}
